# Generated by Django 5.0.6 on 2024-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_device_latitude_device_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='grafana_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
